name: Build Documentation

on:
  workflow_call: ~
  workflow_dispatch: ~
  push:
    branches: [master]
    paths:
      - "docs/**"
jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install -y sed jq git
          pip install --upgrade sphinx_rtd_theme myst-parser sphinx docutils sphinx-sitemap sphinxcontrib-spelling sphinx-tabs sphinxcontrib-youtube pygments breathe sphinx-copybutton

      - uses: actions/checkout@v3
        with:
          path: current_repo

      - name: Build doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: current_repo/docs/build.sh
        shell: bash

      - name: Upload documetation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./gh-pages
