name: Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch: ~

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build doc
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Upload documetation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/html/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: DocumentationHTML
          path: docs/_build/html/
