name: publish release

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: "Version name"
        required: true

jobs:
  build_docs:
    uses: ./.github/workflows/build_doc.yml

  edit_release:
    runs-on: ubuntu-latest
    needs: [build_docs]
    steps:
      - name: Edit release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit supervisor_${{inputs.version_name}} --draft=false
